version: "1"

services:
  frontend:
    context: "./frontend/neuro_fe"
    dockerfile: "./build.Dockerfile"
    command: 'node server.js'
    ports:
      - "3000:3000"
    

  backend:
    build:
      context: "./neuro_prediction"
      dockerfile: "./build_nogpu.Dockerfile"
    command: > 
      bash -c "
      python3 manage.py makemigrations main && 
      python3 manage.py migrate && 
      python3 manage.py shell < populate.py &&
      gunicorn --bind 0.0.0.0:8000 --workers 3 neuro_prediction.wsgi:application"
    volumes:
      - "./media:/app/media"
    ports:
      - "8000:8000"
    depends_on:
      postgres-db:
        condition: service_healthy
    links:
      - "postgres-db"


  postgres-db:
    image: "postgres:16.2-alpine3.19"
    restart: "always"
    volumes:
      - "./postgres_db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password123"
      POSTGRES_USER: "postgres_user"
      POSTGRES_DB: "postgres_db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres_db -U postgres_user"]
      interval: 10s
      timeout: 10s
      retries: 5